[package]
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
description = "Mavlink Camera Manager"
edition = "2021"
license = "MIT"
name = "mavlink-camera-manager"
version = "0.2.4"

documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
readme = "README.md"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

default-run = "mavlink-camera-manager"
path = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
name = "mavlink-camera-manager"
path = "src/main.rs"

[dependencies]
clap = "2"
regex = "1.3"

#TODO: Investigate rweb to use openapi spec for free
# https://github.com/kdy1/rweb
actix-web = "3.3.2"
serde = "^1.0.8"
serde_derive = "^1.0.8"
serde_json = "^1.0.41"

## FINAL
sys-info = "0.8.0"
chrono = "0.4.19"
env_logger = "0.8.3"
lazy_static = "1.4.0"
log = "0.4"
paperclip = {version = "0.6.1", features = ["actix", "swagger-ui", "url"]}
#TODO: Replace it with yaserde
quick-xml = {version = "0.21", features = ["serialize"]}
simple-error = "0.2"
url = {version = "2", features = ["serde"]}
v4l = "0.12.0"
directories = "3.0.1"
pnet = "0.27.2"

## Mavlink
mavlink = {version = "0.8.6", features = ["default", "emit-extensions"]}

## RTSP server
glib = {version = "0.15.0", optional = true}
gstreamer = {version = "0.18.0", optional = true}
gstreamer-rtsp-server = {version = "0.18.0", optional = true}

[dev-dependencies]
rand = "0.8"

[build-dependencies]
reqwest = {version = "0.11", features = ["blocking"]}
vergen = {version = "4", default-features = false, features = ["build", "git"]}

[features]
default = ["rtsp"]
gst = ["glib", "gstreamer"]
rtsp = ["gst", "gstreamer-rtsp-server"]
